import torch
import math
import torch.nn as nn
import warnings
import os

DEVICE_TYPE = os.environ.get("DEVICE_TYPE", "GPU")

def manual_cdist(x, y, eps=1e-9):
    """
    rewrite torch.cdist for NPU usage
    """
    B, N, C = x.shape
    _, M, _ = y.shape
    x_square = (x ** 2).sum(dim=2, keepdim=True)
    y_square = (y ** 2).sum(dim=2, keepdim=True).transpose(1, 2)
    cross_term = torch.bmm(x, y.transpose(1, 2))
    dist = torch.clamp(x_square + y_square - 2 * cross_term, min=0.0)
    return torch.sqrt(dist + eps)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.", stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    try:
        return _no_grad_trunc_normal_(tensor, mean, std, a, b)
    except:
        return tensor

def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output

class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    """
    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)

def index_points(points, idx):
    """Sample features following the index.

    Returns:
        new_points:, indexed points data, [B, S, C]

    Args:
        points: input points data, [B, N, C]
        idx: sample index data, [B, S]
    """
    device = points.device
    B = points.shape[0]
    view_shape = list(idx.shape)
    view_shape[1:] = [1] * (len(view_shape) - 1)
    repeat_shape = list(idx.shape)
    repeat_shape[0] = 1
    batch_indices = torch.arange(B, dtype=torch.long).to(device).view(view_shape).repeat(repeat_shape)
    new_points = points[batch_indices, idx, :]
    return new_points

def cluster_dpc_knn(token_dict, cluster_num, k=5, token_mask=None):
    """Cluster tokens with DPC-KNN algorithm.

    Args:
        token_dict (dict): dict for token information
        cluster_num (int): cluster number
        k (int): number of the nearest neighbor used for local density.
        token_mask (Tensor[B, N]): mask indicate the whether the token is
            padded empty token. Non-zero value means the token is meaningful,
            zero value means the token is an empty token. If set to None, all
            tokens are regarded as meaningful.

    Return:
        idx_cluster (Tensor[B, N]): cluster index of each token.
        cluster_num (int): actual cluster number.
            The same with input cluster number.
    """
    with torch.no_grad():
        x = token_dict["x"]
        B, N, C = x.shape 

        if DEVICE_TYPE == "NPU":
            dist_matrix = manual_cdist(x, x).float() / (C ** 0.5)
        else:
            dist_matrix = torch.cdist(x.float(), x.float()) / (C ** 0.5)  

        if token_mask is not None:
            token_mask = token_mask > 0
            # in order to not affect the local density, the distance between empty tokens
            # and any other tokens should be the maximal distance.
            dist_matrix = dist_matrix * token_mask[:, None, :] + \
                          (dist_matrix.max() + 1) * (~token_mask[:, None, :])

        # get local density
        dist_nearest, index_nearest = torch.topk(dist_matrix, k=k, dim=-1, largest=False)  
        density = (-(dist_nearest ** 2).mean(dim=-1)).exp()  

        # add a little noise to ensure no tokens have the same density.
        density = density + torch.rand(
            density.shape, device=density.device, dtype=density.dtype) * 1e-6

        if token_mask is not None:
            # the density of empty token should be 0
            density = density * token_mask

        # get distance indicator
        mask = density[:, None, :] > density[:, :, None]
        mask = mask.type(x.dtype)
        dist_max = dist_matrix.flatten(1).max(dim=-1)[0][:, None, None]
        dist, index_parent = (dist_matrix * mask + dist_max * (1 - mask)).min(dim=-1)

        # select clustering center according to score
        score = dist * density
        _, index_down = torch.topk(score, k=cluster_num, dim=-1)

        # assign tokens to the nearest center
        dist_matrix = index_points(dist_matrix, index_down)

        idx_cluster = dist_matrix.argmin(dim=1)

        # make sure cluster center merge to itself
        idx_batch = torch.arange(B, device=x.device)[:, None].expand(B, cluster_num)
        idx_tmp = torch.arange(cluster_num, device=x.device)[None, :].expand(B, cluster_num)
        idx_cluster[idx_batch.reshape(-1), index_down.reshape(-1)] = idx_tmp.reshape(-1)
    return idx_cluster, cluster_num

def select_pos(idx_cluster, pos_weight, init_pos=None):
    ori_tensor = torch.cat((idx_cluster.to(float),pos_weight.to(float)),dim=0)
    sort_tensor, indices = torch.sort(ori_tensor.transpose(0,1), dim=0)
    _, counts = torch.unique_consecutive(sort_tensor[:, 0].to(torch.float), return_inverse=False, return_counts=True)
    cumsum_rows = torch.cumsum(counts,dim=0) - 1
    pos_index = indices[:,0]
    final_pos_idx = torch.gather(pos_index,dim=0,index=cumsum_rows)

    if init_pos is not None:
        final_pos = torch.gather(init_pos,dim=1,index=final_pos_idx.unsqueeze(0)) 
        return final_pos_idx, final_pos
    else:
        return final_pos_idx

def select_pos_topk(idx_cluster, pos_weight, k=1, init_pos=None):
    ori_tensor = torch.cat((idx_cluster.to(float),pos_weight.to(float)),dim=0)
    sort_tensor, indices = torch.sort(ori_tensor.transpose(0,1), dim=0)
    _, counts = torch.unique_consecutive(sort_tensor[:, 0].to(torch.float), return_inverse=False, return_counts=True)
    
    counts_offset_list = [counts * 0] 
    cumsum_rows = torch.cumsum(counts, dim=0) - 1
    cumsum_rows_list = [cumsum_rows]
    for i in range(2, k+1): 
        counts_offset = counts_offset_list[-1] - 1 
        counts_offset = counts_offset + ((counts_offset+counts)<=0) * (-counts_offset)
        counts_offset_list.append(counts_offset) 
        cur_cumsum_rows = cumsum_rows + counts_offset 
        cumsum_rows_list.append(cur_cumsum_rows)
    
    final_pos_idx_list = [] 
    for cumsum_rows in cumsum_rows_list:
        pos_index = indices[:,0]
        final_pos_idx = torch.gather(pos_index,dim=0,index=cumsum_rows) 
        final_pos_idx_list.append(final_pos_idx.unsqueeze(-1))
    final_pos_idx = torch.cat(final_pos_idx_list, dim=-1) # (n, k)

    if init_pos is not None:
        final_pos = torch.gather(init_pos,dim=1,index=final_pos_idx.unsqueeze(0)) 
        return final_pos_idx, final_pos
    else:
        return final_pos_idx

def merge_tokens(token_dict, idx_cluster, cluster_num, token_weight=None, stage=0):
    """ Merge tokens in the same cluster to a single cluster.
    Implemented by torch.index_add(). Flops: B*N*(C+2)

    Args:
        token_dict (dict): dict for input token information
        idx_cluster (Tensor[B, N]): cluster index of each token.
        cluster_num (int): cluster number
        token_weight (Tensor[B, N, 1]): weight for each token.

    Return:
        out_dict (dict): dict for output token information
    """
    # token_dict.keys()  # ['x', 'token_num', 'idx_token', 'agg_weight', 'mask']
    x = token_dict['x'] 
    idx_token = token_dict['idx_token']  
    agg_weight = token_dict['agg_weight']  
    position_ids = token_dict["position_ids"]
    # PPE, position_ids shape: [3,...] -> [3*ppe_k,...]
    ppe_k = token_dict.get("ppe_k")

    B, N, C = x.shape
    if token_weight is None:
        token_weight = x.new_ones(B, N, 1)

    idx_batch = torch.arange(B, device=x.device)[:, None]  
    idx = idx_cluster + idx_batch * cluster_num

    all_weight = token_weight.new_zeros(B * cluster_num, 1) 
    all_weight.index_add_(dim=0, index=idx.reshape(B * N),
                          source=token_weight.reshape(B * N, 1))
    all_weight = all_weight + 1e-6
    norm_weight = token_weight / all_weight[idx]

    x_merged = x.new_zeros(B * cluster_num, C) 
    source = x * norm_weight

    x_merged.index_add_(dim=0, index=idx.reshape(B * N),
                        source=source.reshape(B * N, C).type(x.dtype))
    x_merged = x_merged.reshape(B, cluster_num, C) 

    idx_token_new = index_points(idx_cluster[..., None], idx_token).squeeze(-1)
    weight_t = index_points(norm_weight, idx_token)
    agg_weight_new = agg_weight * weight_t
    agg_weight_new / agg_weight_new.max(dim=1, keepdim=True)[0]

    if position_ids is not None:
        if ppe_k:
            position_sections = 3
            reserve_num = ppe_k
            assert (position_sections*reserve_num) % position_ids.shape[0] == 0
            final_pos_idx = select_pos_topk(idx_cluster, 
                                            token_weight.squeeze(-1), 
                                            k=position_sections*reserve_num//position_ids.shape[0])
            new_position_ids_list = []
            for k in range(final_pos_idx.shape[-1]):
                new_position_ids_list.append(torch.index_select(position_ids, 1, final_pos_idx[:, k]).unsqueeze(0))
            new_position_ids = torch.cat(new_position_ids_list, dim=0) 
            new_position_ids = new_position_ids.transpose(1,0).reshape(-1, new_position_ids.shape[-1])

        else:
            final_pos_idx = select_pos(idx_cluster, token_weight.squeeze(-1))
            new_position_ids = torch.index_select(position_ids, 1, final_pos_idx) 
    else:
        new_position_ids = position_ids

    out_dict = {}
    out_dict['x'] = x_merged
    out_dict['token_num'] = cluster_num
    out_dict['idx_token'] = idx_token_new
    out_dict['agg_weight'] = agg_weight_new
    out_dict['mask'] = None
    out_dict['position_ids'] = new_position_ids
    if ppe_k:
        out_dict["ppe_k"] = ppe_k
    return out_dict

class CTM(nn.Module):
    def __init__(self, sample_ratio, k=5):
        super().__init__()
        self.sample_ratio = sample_ratio
        self.k = k
        # print('sample_ratio:', sample_ratio, 'k:', k)

    def forward(self, token_dict, sample_ratio=None, stage=0):
        x = token_dict["x"]
        B, N, C = x.shape

        token_weight = x.new_ones(B, N)

        if token_dict["mask"] is not None:
            token_weight.masked_fill_((1 - token_dict["mask"]).to(torch.bool), float("-inf"))
        token_weight = token_weight.unsqueeze(2)
        token_dict['x'] = x

        if sample_ratio is not None:
            cluster_num = max(math.ceil(N * sample_ratio), 1)
        elif self.sample_ratio > 1:
            cluster_num = max(math.ceil(self.sample_ratio), 1)
        else:
            cluster_num = max(math.ceil(N * self.sample_ratio), 1)

        k = min(3, max(cluster_num//2, 1)) if self.k > cluster_num else self.k

        ''' cluster '''
        idx_cluster, cluster_num = cluster_dpc_knn(
            token_dict, cluster_num, k, token_mask=token_dict["mask"])

        ''' merge tokens '''
        down_dict = merge_tokens(token_dict, idx_cluster, cluster_num, token_weight, stage=stage)

        return down_dict
